# Generated by Django 5.2 on 2025-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coreuser', '0002_alter_coreuser_created_at_alter_coreuser_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreuser',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
