# Generated by Django 5.2 on 2025-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coreuser', '0003_alter_coreuser_options_alter_coreuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='role',
            field=models.IntegerField(choices=[(1, '员工'), (2, '部门经理'), (3, '人事管理')], default=1, help_text='1-员工，2-部门经理，3-人事管理', verbose_name='用户角色'),
        ),
    ]
