# Generated by Django 5.2 on 2025-05-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coreuser', '0003_alter_coreuser_options_alter_coreuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_duty_time', models.TimeField(default='09:00:00', help_text='默认早上9点', verbose_name='到岗时间')),
                ('off_duty_time', models.TimeField(default='18:00:00', help_text='默认下午6点', verbose_name='下岗时间')),
                ('working_hours', models.FloatField(default=8.0, help_text='默认8小时', verbose_name='当日工时')),
                ('late_threshold', models.IntegerField(default=30, help_text='默认30分钟', verbose_name='迟到阈值')),
                ('early_threshold', models.IntegerField(default=30, help_text='默认30分钟', verbose_name='早退阈值')),
                ('user', models.OneToOneField(help_text='关联到Coreuser模型的用户信息', on_delete=django.db.models.deletion.CASCADE, to='Coreuser.coreuser', verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '考勤规则',
                'verbose_name_plural': '考勤规则',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='当日中第一次签到时记录的时间', null=True, verbose_name='签到时间')),
                ('check_out_time', models.DateTimeField(blank=True, help_text='当日中第二次签到时记录的时间', null=True, verbose_name='签退时间')),
                ('date', models.DateField(help_text='考勤记录的日期', verbose_name='日期')),
                ('user', models.ForeignKey(help_text='关联到Coreuser模型的用户信息', on_delete=django.db.models.deletion.CASCADE, to='Coreuser.coreuser', verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '日考勤',
                'verbose_name_plural': '日考勤',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.IntegerField(default=0, help_text='默认为0', verbose_name='工作天数')),
                ('month', models.DateField(help_text='考勤记录的月份', verbose_name='月份')),
                ('user', models.ForeignKey(help_text='关联到Coreuser模型的用户信息', on_delete=django.db.models.deletion.CASCADE, to='Coreuser.coreuser', verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '月考勤',
                'verbose_name_plural': '月考勤',
            },
        ),
    ]
