# Generated by Django 5.2 on 2025-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='location',
            field=models.CharField(blank=True, help_text='如：总部A区闸机', max_length=255, null=True, verbose_name='打卡地点'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(default='未打卡', help_text='根据考勤规则自动计算的状态：正常、迟到、早退、旷工半天、全勤等', max_length=20, verbose_name='考勤状态'),
        ),
    ]
